config/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = ([
    path('admin/', admin.site.urls),
    path('' , include('home.urls' , namespace='home')),
    path('accounts/' , include('accounts.urls' , namespace='accounts')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+
               static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('' , views.home , name = 'home') ,
    path('products/' ,views.all_product , name ='products'),
    path('detail/<int:id>/' , views.product_detail , name = 'detail'),
    path('category/<slug>/<int:id>/' , views.all_product , name = 'category'),
]

home/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Category(models.Model) :
    sun_category=models.ForeignKey('self',on_delete=models.CASCADE,null=True,blank=True,related_name='sub')
    sub_cat=models.BooleanField(default=False)

    name = models.CharField(max_length=100)
    create = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    slug = models.SlugField(allow_unicode=True , unique=True,blank=True , null=True)
    image = models.ImageField(upload_to='Category',null=True,blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return  reverse('home:category', args=[self.slug, self.id])



class Product(models.Model) :
    category = models.ManyToManyField(Category,blank=True)
    name = models.CharField(max_length=100)
    amount = models.PositiveSmallIntegerField()
    unit_price = models.PositiveIntegerField()
    discount = models.PositiveSmallIntegerField(blank=True , null=True)
    total_price = models.PositiveIntegerField()
    information = models.TextField(blank=True , null=True)
    create = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    available = models.BooleanField(default=True)
    image = models.ImageField(upload_to='Product')

    def __str__(self):
        return self.name

    @property
    def total_price(self):
        if not self.discount :
            return self.unit_price
        elif self.discount :
            total = (self.discount * self.unit_price) / 100
            return int(self.unit_price - total)
        return self.total_price

home/views.py
from django.shortcuts import render
from .models import *


# Create your views here.

def home(request):
    category = Category.objects.filter(sub_cat=False)
    return render(request , 'home/home.html',{'category':category})

def all_product(request,slug=None,id=None):
    products = Product.objects.all()
    category = Category.objects.filter(sub_cat=False)
    if slug and id:
        data = Category.objects.get(slug = slug , id=id)
        products = products.filter(category = data)
    return render(request , 'home/products.html' ,{'products':products,'category':category})


def product_detail(request , id):
    product = Product.objects.get(id = id)
    return render(request ,'home/detail.html' , {'product':product})

home/templates/home/detail.html
{% extends '_base.html' %}
{% block body %}
    <h1>{{ product.name }}</h1>
    <img src="{{ product.image.url }}" width="200" alt="{{ product.name }}">
    <h4>قیمت : {{ product.total_price }}</h4>
    <p>{{ product.information }}</p>
{% endblock %}

home/templates/home/home.html
{% extends '_base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'home/category.css' %}">
{% endblock %}

{% block title %}
    صفحه اصلی
{% endblock %}
{% block body %}
    {% for cat in category %}
        <div class="card">
           <a href="{{ cat.get_absolute_url }}">
               <h1>{{ cat.name }}</h1>

                <img src="{{ cat.image.url }}" width="400" alt="{{ cat.name }}" title="عکس دسته بندی موبایل">
           </a>
        </div>

    {% endfor %}
{% endblock %}

home/templates/home/products.html
{% extends '_base.html' %}
{% block body %}
    {% for data in category %}
        <a href="{{ data.get_absolute_url }}">{{ data.name }}</a>
        <div class="btn-group">
            <button type="button" class="btn btn-danger dropdown-toggle"
                    data-bs-toggle="dropdown"
                    aria-expanded="false">
            </button>
            <ul class="dropdown-menu">
                {% for info in data.sub.all %}
                    <li><a class="dropdown-item"
                           href="{{ info.get_absolute_url }}">{{ info.name }}</a></li>
                {% endfor %}
            </ul>
        </div>
    {% endfor %}



    {% for product in  products %}
        <h1>{{ product.name }}</h1>
        <a href="{% url 'home:detail' product.id %}">
            <img src="{{ product.image.url }}" alt="{{ product.name }}"
                 title="{{ product.information }}">
        </a>
        {% if product.discount %}
            <h4 style="text-decoration: line-through">قیمت : {{ product.unit_price }}</h4>
            <h3>{{ product.total_price }}</h3>
        {% else %}
            <h3>{{ product.total_price }}</h3>
        {% endif %}

        <a href="{% url 'home:detail' product.id %}" class="btn btn-info">جزییات</a>
        <hr>
    {% endfor %}

{% endblock %}