accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/' , views.user_register , name = 'user_register'),
    path('login/' , views.user_login , name = 'login'),
    path('logout/' , views.user_logout , name ='logout'),
    path('profile/' , views.user_profile , name = 'profile'),
    path('update/' , views.user_update , name = 'update'),
    path('change/' , views.change_password , name = 'change'),
]

config/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = ([
    path('admin/', admin.site.urls),
    path('' , include('home.urls' , namespace='home')),
    path('accounts/' , include('accounts.urls' , namespace='accounts')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+
               static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('' , views.home , name = 'home') ,
    path('products/' ,views.all_product , name ='products'),
    path('detail/<int:id>/' , views.product_detail , name = 'detail'),
    path('category/<slug>/<int:id>/' , views.all_product , name = 'category'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

# Create your models here.
class Profile(models.Model) :
    user = models.OneToOneField(User , on_delete=models.CASCADE)
    phone = models.IntegerField(null=True , blank=True)
    address = models.TextField(null=True , blank=True)
    profile_image  = models.ImageField(upload_to='Profile' , default='1.jpg')

    def __str__(self):
        return self.user.username


def save_profile_user(sender , **kwargs) :
    if kwargs['created'] :
        profile_user = Profile(user = kwargs['instance'])
        profile_user.save()

post_save.connect(save_profile_user,sender = User)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import *

error = {
    'min_length' : 'حداقل می بایست 5 کاراکتر باشد',
    'required' : 'این فیلد اجباری است',
}

class UserRegisterForm(forms.Form):
    user_name = (
        forms.CharField(max_length=50 ,
    widget=forms.TextInput(attrs={'placeholder' : 'نام کاربری خود را وارد نمایید'}) ,  error_messages=error) )
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder' : 'email....'}) , error_messages=error)
    first_name = forms.CharField(max_length=10 , min_length=5 , error_messages=error)
    last_name = forms.CharField(max_length=100 , error_messages=error)
    password_1 = (
        forms.CharField(max_length=100 ,
                        widget=forms.PasswordInput(attrs={'placeholder' : 'پسورد ...'})))
    password_2 = forms.CharField(max_length=100, widget=forms.PasswordInput(attrs={'placeholder' : 'تکرار پسورد ...'}))

    def clean_user_name(self):
        user = self.cleaned_data['user_name']
        if User.objects.filter(username = user).exists():
            raise forms.ValidationError('نام کاربری تکرای است')
        return user

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email = email).exists():
            raise forms.ValidationError('ایمیل تکراری است')
        return email

    def clean_password_2(self):
        password1 = self.cleaned_data['password_1']
        password2 = self.cleaned_data['password_2']
        if password1 != password2 :
            raise forms.ValidationError('Password not match')
        elif len(password2) < 8 :
            raise forms.ValidationError('پسورد می بایست حداقل 8 کارکتر باشد')
        elif not any(x.isupper() for x in password2):
            raise forms.ValidationError('پسورد می بایست شامل حداقل یک حرف بزرگ باشد')
        return password2


class UserLoginForm(forms.Form):
    user = forms.CharField()
    password = forms.CharField()

class UserUpdateForm(forms.ModelForm) :
    class Meta:
        model = User
        fields = ['email' , 'first_name' , 'last_name']

class ProfileUpdateForm(forms.ModelForm) :
    class Meta:
        model = Profile
        fields = ['phone' , 'address' , 'profile_image']

accounts/views.py
from django.shortcuts import render , redirect
from .forms import *
from django.contrib.auth.models import User
from django.contrib.auth import authenticate , login , logout
from django.contrib import messages
from .models import *
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
# Create your views here.

def user_register(request):
    if request.method == 'POST' :
        form = UserRegisterForm(request.POST)
        if form.is_valid() :
            data = form.cleaned_data
            user = User.objects.create_user(
                username = data['user_name'] ,
                email = data['email'] ,
                first_name = data['first_name'],
                last_name = data['last_name'] ,
                password = data['password_2']
            )
            user.save()
            messages.success(request , 'ثبت نام شما با موفقیت انجام شد'  ,'success')
            return redirect('home:home')
    else :
        form = UserRegisterForm()
    return render(request , 'accounts/register.html',{'form':form})




def user_login(request) :
    if request.method == 'POST' :
        form = UserLoginForm(request.POST)
        if form.is_valid() :
            data = form.cleaned_data
            user = authenticate(request ,
                                username = data['user'] , password = data['password'])
            if user is not None :
                login(request , user)
                messages.success(request , 'خوش آمدید' , 'primary')
                return redirect('home:home')
            else:
                messages.error(request , 'نام کاربری یا رمز عبور اشتباه است' , 'danger')

    else :
        form = UserLoginForm()
    return render(request,'accounts/login.html',{'form':form})

def user_logout(request):
    logout(request)
    messages.success(request,'به امید دیدار' , 'info')
    return redirect('home:home')


@login_required(login_url='accounts:login')
def user_profile(request):
    profile = Profile.objects.get(user_id = request.user.id)
    return render(request , 'accounts/profile.html',
                  {'profile':profile})



@login_required(login_url='accounts:login')
def user_update(request):
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST,instance=request.user)
        profile_form = ProfileUpdateForm(request.POST,request.FILES,instance=request.user.profile)
        if user_form and profile_form.is_valid() :
            user_form.save()
            profile_form.save()
            return redirect('accounts:profile')
    else :
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance= request.user.profile)
    return render(request , 'accounts/update.html',
                  {'user_form':user_form ,'profile_form':profile_form})

@login_required(login_url='accounts:login')
def change_password(request) :
    if request.method == 'POST' :
        form = PasswordChangeForm(request.user , request.POST)
        if form.is_valid() :
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('accounts:profile')
    else :
        form = PasswordChangeForm(request.user)

    return render(request ,'accounts/change.html',{'form':form})

accounts/templates/accounts/change.html
{% extends '_base.html' %}
{% block body %}
	<form method="post">
        {% csrf_token %}
        {{ form.as_p }}
{#        <input type="password" placeholder="پسورد قبلی خو د را وارد نمایید" name="old_password">#}
{#        <br><br>#}
{#        <input type="password" placeholder="پسورد جدید خو د را وارد نمایید" name="new_password1">#}
{#        <br><br>#}
{#        <input type="password" placeholder="پسورد جدید خو د را مجدد دوباره تکرار نمایید" name="new_password2">#}
{#        <br><br>#}
        <button type="submit">Password Change</button>

    </form>
{% endblock %}

accounts/templates/accounts/login.html
{% extends '_base.html' %}
{% block title %}
	ورود کاربر
{% endblock %}
{% block body %}
	<form method="post">
        {% csrf_token %}
{#        {{ form.as_p }}#}
        <input type="text" name="user" placeholder="نام کاربری ...">
        <input type="password" name="password" placeholder="رمز عبور ...">
        <button type="submit">Login</button>
    </form>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends '_base.html' %}
{% block title %}
    پروفایل
{% endblock %}
{% block body %}
    <table>
        <tr>
            <th>نام کاربری : {{ profile.user.username }}</th>
        </tr>
        <tr>
            <th>پست الکترونیکی : {{ profile.user.email }}</th>
        </tr>
        <tr>
            <th>نام : {{ profile.user.first_name }}</th>
        </tr>
        <tr>
            <th>نام خانوادگی : {{ profile.user.last_name }}</th>
        </tr>
        <tr>
            <th>همراه : {{ profile.phone }}</th>
        </tr>
        <tr>
            <th>آدرس : {{ profile.address }}</th>
        </tr>
    <tr>
        <img src="{{ profile.profile_image.url }}"
             alt="{{ profile.user.username }}" width="300">
    </tr>
    </table>
    <a href="{% url 'accounts:update' %}" class="btn btn-warning">Update</a>
    <a href="{% url 'accounts:change' %}" class="btn btn-danger">Change Password</a>
{% endblock %}

accounts/templates/accounts/register.html
{% extends '_base.html' %}
{% block title %}
	صفحه ایجاد کاربر
{% endblock %}
{% block body %}
	<form method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Register</button>
    </form>
{% endblock %}

accounts/templates/accounts/update.html
{% extends '_base.html' %}
{% block body %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
    <button class="btn btn-primary">Update</button>
    </form>
{% endblock %}