accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/' , views.user_register , name = 'user_register'),
    path('login/' , views.user_login , name = 'login'),
    path('logout/' , views.user_logout , name ='logout'),
    path('profile/' , views.user_profile , name = 'profile'),
    path('update/' , views.user_update , name = 'update'),
    path('change/' , views.change_password , name = 'change'),
]

config/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = ([
    path('admin/', admin.site.urls),
    path('' , include('home.urls' , namespace='home')),
    path('accounts/' , include('accounts.urls' , namespace='accounts')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+
               static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('' , views.home , name = 'home') ,
    path('products/' ,views.all_product , name ='products'),
    path('detail/<int:id>/' , views.product_detail , name = 'detail'),
    path('category/<slug>/<int:id>/' , views.all_product , name = 'category'),
]

templates/_base.html
<!DOCTYPE html>
<html lang="en" dir="rtl">
<head>
    <meta charset="UTF-8">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.rtl.min.css" integrity="sha384-+qdLaIRZfNu4cVPK/PxJJEy0B0f3Ugv8i482AKY7gwXwhaCroABd086ybrVKTa0q" crossorigin="anonymous">
    {% block css %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% include 'navbar.html' %}
    <div class="container">
        {% include 'message.html' %}
        {% block body %}

    {% endblock %}
    </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

</body>
</html>

templates/message.html
{% if messages %}
    {% for msg in messages %}
        <h3 {% if msg.tags %} class="alert alert-{{ msg.tags }}" {% endif %}>{{ msg }}</h3>
    {% endfor %}
{% endif %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page"
                       href="{% url 'home:home' %}">صفحه اصلی</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link active" aria-current="page"
                       href="{% url 'home:products' %}">محصولات</a>
                </li>

                {% if user.is_authenticated %}
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:profile' %}">پروفایل</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:logout' %}">خروج</a>
                    </li>
                {% else %}

                    <li class="nav-item">
                        <a class="nav-link " href="{% url 'accounts:login' %}">ورود</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link "
                           href="{% url 'accounts:user_register' %}">ثبت نام</a>
                    </li>
                {% endif %}
            </ul>

        </div>
    </div>
</nav>